GTpose.o: GTpose.cc ../../libs/util/system.h ../../libs/util/defines.h \
 ../../libs/util/timer.h ../../libs/util/arguments.h \
 ../../libs/util/strings.h ../../libs/util/exception.h \
 ../../libs/util/file_system.h ../../libs/util/tokenizer.h \
 ../../libs/mve/scene.h ../../libs/mve/defines.h ../../libs/mve/view.h \
 ../../libs/mve/camera.h ../../libs/mve/image_base.h \
 ../../libs/mve/image.h ../../libs/math/functions.h \
 ../../libs/math/defines.h ../../libs/math/vector.h \
 ../../libs/math/algo.h ../../libs/math/matrix.h ../../libs/mve/bundle.h \
 ../../libs/mve/mesh.h ../../libs/mve/bundle_io.h \
 ../../libs/mve/image_tools.h ../../libs/math/accum.h
