sceneupgrade.o: sceneupgrade.cc ../../libs/util/system.h \
 ../../libs/util/defines.h ../../libs/util/arguments.h \
 ../../libs/util/strings.h ../../libs/util/exception.h \
 ../../libs/util/file_system.h ../../libs/mve/view.h \
 ../../libs/mve/defines.h ../../libs/mve/camera.h \
 ../../libs/mve/image_base.h ../../libs/mve/image.h \
 ../../libs/math/functions.h ../../libs/math/defines.h \
 ../../libs/math/vector.h ../../libs/math/algo.h ../../libs/math/matrix.h \
 ../../libs/sfm/bundler_common.h ../../libs/util/aligned_memory.h \
 ../../libs/util/aligned_allocator.h ../../libs/sfm/camera_pose.h \
 ../../libs/math/matrix_tools.h ../../libs/sfm/defines.h \
 ../../libs/sfm/correspondence.h ../../libs/sfm/feature_set.h \
 ../../libs/sfm/sift.h ../../libs/sfm/surf.h ../../libs/sfm/defines.h
