os: linux
language: cpp
compiler: gcc
sudo: false

branches:
   only:
     - master
     - develop

before_install:
   - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; fi
   - wget https://github.com/google/googletest/archive/master.zip -O /tmp/gtest.zip
   - unzip /tmp/gtest.zip
   - cd googletest-master/googletest
   - cmake .
   - make
   - sudo cp -a include/gtest /usr/include
   - sudo cp -a libgtest_main.a libgtest.a /usr/lib/
   - cd "${TRAVIS_BUILD_DIR}"

addons:
   apt:
     sources:
       - ubuntu-toolchain-r-test
     packages:
       - g++-4.8

before_script:
   - git clone https://github.com/simonfuhrmann/mve ../mve

script:
    - make -C ../mve
    - make
    - make test
    - ./tests/test
